"""empty message

Revision ID: 171fb5b3a27f
Revises: 
Create Date: 2019-04-26 11:23:21.180414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171fb5b3a27f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
